# Generated by Django 4.2.6 on 2023-10-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
